version: '3.9'

services:
  redis:
    image: redis:alpine
    container_name: notecraft_redis
    ports:
      - "6379:6379"

  backend:
    build:
      context: ./NoteCraft_backend
      dockerfile: Dockerfile.web
    container_name: notecraft_backend
    ports:
      - "8000:8000"
    volumes:
      - ./NoteCraft_backend:/app
    env_file:
      - ./NoteCraft_backend/.env
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis

  celery:
    build:
      context: ./NoteCraft_backend
      dockerfile: Dockerfile.celery
    container_name: notecraft_celery
    volumes:
      - ./NoteCraft_backend:/app
    env_file:
      - ./NoteCraft_backend/.env
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - backend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: notecraft_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
